server:
  port: 8090
spring:
  cloud:
    gateway:
      routes:
      - id: micro1
        uri: http://localhost:8022
        predicates:
        - Path=/client/**
      - id: micro2
        uri: http://localhost:8023
        predicates:
        - Path=/transaction/**
      - id: micro3
        uri: http://localhost:8092
        predicates:
        - Path=/consults/**